### ISSUE TITLE
Solaris dark and light are both same

### ISSUE THREAD

**Issue by M-ZubairAhmed** [dawnlabs/carbon#134]
#### Overview
There seems to be no change among themes for Solarized(dark) & Solarized(light).
#### Browser
Firefox 56.0 -64bit
Mozilla firefox for ubuntu
canonical 1.0
#### Reproduction
- I imported the code to the editor
- Toggled between two solaris themes
- No change in theme appeared

#### Dark solaris from atom
![image](https://user-images.githubusercontent.com/17708702/32264696-f11b8a06-bf05-11e7-94ec-c5e781ce245f.png)

#### Dark
![image](https://user-images.githubusercontent.com/17708702/32264590-68226238-bf05-11e7-83ad-6a19cba865ea.png)
#### Light
![image](https://user-images.githubusercontent.com/17708702/32264601-7b294d88-bf05-11e7-98fb-2818d0de0cb2.png)

**Comment by M-ZubairAhmed** [comment]
If this issue is revelant, i would like to work on this

**Comment by jakedex** [comment]
Reproducible on my end as well, this is definitely an issue. Thanks for reporting, @M-ZubairAhmed!

**Comment by Drarok** [comment]
I worked on this previously:
https://github.com/dawnlabs/carbon/issues/113
https://github.com/dawnlabs/carbon/pull/118

Not sure what's gone wrong between then and now!

**Comment by Drarok** [comment]
Ah ha! This commit broke it: https://github.com/dawnlabs/carbon/commit/830828d6c56ef7e0ed485d853b1b63e837594933

**Comment by M-ZubairAhmed** [comment]
would you guys still want me to go ahead with this issue or it is solved in the above pull requests?

**Comment by Drarok** [comment]
Not solved, just thought I'd lend a hand to find what the issue is since I'd worked on those themes previously. Please, go ahead. 🙂

**Comment by mfix22** [comment]
Thanks @Drarok! This will be out in the next release. Sorry about breaking it for all you Solarized fans!
